# Generated by Django 4.2.16 on 2025-08-23 07:53

import app.utils.time_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "App Setting",
                "verbose_name_plural": "App Settings",
            },
        ),
        migrations.CreateModel(
            name="ElectricityPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "start_time",
                    models.DateTimeField(
                        default=app.utils.time_utils.TimeUtils.now_utc
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=app.utils.time_utils.TimeUtils.now_utc
                    ),
                ),
                ("price_kwh", models.DecimalField(decimal_places=5, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShellyDevice",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("familiar_name", models.CharField(max_length=255)),
                ("shelly_api_key", models.CharField(max_length=255)),
                (
                    "shelly_device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "last_contact",
                    models.DateTimeField(
                        default=app.utils.time_utils.TimeUtils.now_utc
                    ),
                ),
                (
                    "run_hours_per_day",
                    models.IntegerField(
                        default=0,
                        help_text="Set how many hours the device should run daily (0-24)",
                    ),
                ),
                (
                    "day_transfer_price",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Transfer price during the day (c/kWh)",
                        max_digits=6,
                    ),
                ),
                (
                    "night_transfer_price",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Transfer price during the night (c/kWh)",
                        max_digits=6,
                    ),
                ),
                (
                    "relay_channel",
                    models.IntegerField(
                        default=0,
                        help_text="Default relay channel for the Shelly device (e.g., 0 for switch:0)",
                    ),
                ),
                (
                    "shelly_server",
                    models.URLField(
                        default="https://yourapiaddress.shelly.cloud",
                        help_text="Base URL of the Shelly server used for device communication",
                        max_length=512,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARN", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.shellydevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.shellydevice",
                    ),
                ),
                (
                    "electricity_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.electricityprice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
