# Generated by Django 4.2.16 on 2025-08-24 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC (Coordinated Universal Time)"),
                            ("Europe/Helsinki", "Helsinki (Finland)"),
                            ("Europe/Stockholm", "Stockholm (Sweden)"),
                            ("Europe/Oslo", "Oslo (Norway)"),
                            ("Europe/Copenhagen", "Copenhagen (Denmark)"),
                            ("Europe/London", "London (UK)"),
                            ("Europe/Berlin", "Berlin (Germany)"),
                            ("Europe/Paris", "Paris (France)"),
                            ("Europe/Rome", "Rome (Italy)"),
                            ("Europe/Madrid", "Madrid (Spain)"),
                            ("America/New_York", "New York (EST/EDT)"),
                            ("America/Chicago", "Chicago (CST/CDT)"),
                            ("America/Denver", "Denver (MST/MDT)"),
                            ("America/Los_Angeles", "Los Angeles (PST/PDT)"),
                            ("Asia/Tokyo", "Tokyo (Japan)"),
                            ("Asia/Shanghai", "Shanghai (China)"),
                            ("Asia/Kolkata", "Mumbai/Delhi (India)"),
                            ("Australia/Sydney", "Sydney (Australia)"),
                        ],
                        default="Europe/Helsinki",
                        help_text="User's preferred timezone for displaying dates and times",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
