# Generated by Django 4.2.16 on 2025-08-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShellyTemperature",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("familiar_name", models.CharField(max_length=255)),
                ("shelly_api_key", models.CharField(max_length=255)),
                (
                    "shelly_device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shelly_server",
                    models.URLField(
                        default="https://yourapiaddress.shelly.cloud",
                        help_text="Base URL of the Shelly server used for device communication",
                        max_length=512,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shellydevice",
            name="thermostat_device",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional default thermostat device for this Shelly device",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controlled_devices",
                to="app.shellytemperature",
            ),
        ),
    ]
