# Generated by Django 5.2.9 on 2025-12-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_shellytemperature_and_thermostat_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="shellytemperature",
            name="min_temperature",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum temperature threshold",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="shellytemperature",
            name="max_temperature",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maximum temperature threshold",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="shellytemperature",
            name="hoped_temperature",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Desired temperature setpoint",
                max_digits=5,
                verbose_name="Target temperature",
            ),
        ),
        migrations.AddField(
            model_name="shellytemperature",
            name="current_temperature",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Last recorded temperature reading",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="shellytemperature",
            name="temperature_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last temperature update",
                null=True,
            ),
        ),
    ]
