# Generated by Django 5.2.1 on 2025-06-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_electricityprice_assigned_devices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellydevice',
            name='relay_channel',
            field=models.IntegerField(default=0, help_text='Default relay channel for the Shelly device (e.g., 0 for switch:0)'),
        ),
    ]
