# Generated by Django 5.2.9 on 2025-12-31 13:05

from django.db import migrations


def add_columns_if_missing(apps, schema_editor):
    table = schema_editor.quote_name("app_shellytemperature")

    def existing_columns():
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("PRAGMA table_info(app_shellytemperature)")
            return {row[1] for row in cursor.fetchall()}

    cols = existing_columns()

    def add_column(name, column_sql):
        if name in cols:
            return
        schema_editor.execute(f"ALTER TABLE {table} ADD COLUMN {column_sql}")

    add_column(
        "min_temperature",
        f"{schema_editor.quote_name('min_temperature')} NUMERIC NOT NULL DEFAULT 0",
    )
    add_column(
        "max_temperature",
        f"{schema_editor.quote_name('max_temperature')} NUMERIC NOT NULL DEFAULT 0",
    )
    add_column(
        "hoped_temperature",
        f"{schema_editor.quote_name('hoped_temperature')} NUMERIC NOT NULL DEFAULT 0",
    )
    add_column(
        "current_temperature",
        f"{schema_editor.quote_name('current_temperature')} NUMERIC NOT NULL DEFAULT 0",
    )
    add_column(
        "temperature_updated_at",
        f"{schema_editor.quote_name('temperature_updated_at')} datetime NULL",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_shellytemperature_fields"),
    ]

    operations = [
        migrations.RunPython(add_columns_if_missing, reverse_code=migrations.RunPython.noop),
    ]
