# Generated by Django 5.2.9 on 2025-12-31 13:22

from django.db import migrations, models
import django.db.models.deletion
import app.utils.time_utils


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_shellytemperature_ensure_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_c", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "recorded_at",
                    models.DateTimeField(default=app.utils.time_utils.TimeUtils.now_utc),
                ),
                (
                    "thermostat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_readings",
                        to="app.shellytemperature",
                    ),
                ),
            ],
        ),
    ]
