# Generated by Django 5.1.7 on 2025-03-09 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_kwh', models.DecimalField(decimal_places=5, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_devices', models.TextField(blank=True, null=True)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShellyDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('familiar_name', models.CharField(max_length=255)),
                ('shelly_api_key', models.CharField(max_length=255)),
                ('shelly_device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('last_contact', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_hours_per_day', models.IntegerField(default=0, help_text='Set how many hours the device should run daily (0-24)')),
                ('day_transfer_price', models.DecimalField(decimal_places=5, help_text='Transfer price during the day (c/kWh)', max_digits=6)),
                ('night_transfer_price', models.DecimalField(decimal_places=5, help_text='Transfer price during the night (c/kWh)', max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shellydevice')),
            ],
        ),
    ]
