# Generated by Django 5.1.7 on 2025-03-11 17:44

import app.utils.time_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricityprice',
            name='assigned_devices',
        ),
        migrations.AlterField(
            model_name='electricityprice',
            name='end_time',
            field=models.DateTimeField(default=app.utils.time_utils.TimeUtils.now_utc),
        ),
        migrations.AlterField(
            model_name='electricityprice',
            name='start_time',
            field=models.DateTimeField(default=app.utils.time_utils.TimeUtils.now_utc),
        ),
        migrations.AlterField(
            model_name='shellydevice',
            name='last_contact',
            field=models.DateTimeField(default=app.utils.time_utils.TimeUtils.now_utc),
        ),
    ]
