# Generated by Django 5.2.1 on 2025-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shellydevice_relay_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellydevice',
            name='shelly_server',
            field=models.URLField(default='https://yourapiaddress.shelly.cloud', help_text='Base URL of the Shelly server used for device communication', max_length=512),
        ),
    ]
